### ISSUE TITLE
Upload the source, Luke

### ISSUE THREAD

**Issue by akien-mga** [eugeneloza/Project-Helena#1]
Time to stop procrastinating :P

I don't know if you have it under version control already, but if you don't, you could upload successively your various source snapshots from SourceForge as independent commits, to give some minimal history of the project.

**Comment by eugeneloza** [comment]
@akien-mga, thanks for reminding :D
The problem is that the old source doesn't compile in latest Castle Game Engine version (TCastleControl lost onMouseDown event, which is critical and I cannot replace it easily). The only way to continue development is to completely rewrite the interface (plus port to Android as a bonus). That was a must long ago. But that'd take at least a month or two (I need to create manual mouse events and interface elements. I also need to redraw most of the art in the game)...
At this moment I'm working on the Interface logic creation, but damn it's hard. Now I understand why gamedev companies always have a separate GUI programmist :)
Moreover, when I'm done with interface mechanics I have an urgent task to launch Decoherence game pre-alpha for testing and balancing the battle. As soon as I'm up with a map+enemies+battle mode in Decoherence I could return to Project Helena.
At this moment I see no sense in uploading the code that doesn't even compile (or force users use an obsolete Castle Game Engine version to actually compile it)...

However.... well, there's no problem to do so. I have code of almost all versions since the very first ones... It's easy to commit them one after another... Just an hour or two of simple work.

**Comment by akien-mga** [comment]
> At this moment I see no sense in uploading the code that doesn't even compile (or force users use an obsolete Castle Game Engine version to actually compile it)...

Well it's still useful for the sake of history. Some Castle Game Engine users might find it useful as a reference and want to get inspiration from some of its non-obsolete code chunks. Others might want to help you port the game to the current CGE version, etc.

Sharing code is never a bad thing, even if doesn't compile. You can add a README saying what version of CGE is supported, and that porting it to a more recent version is planned in the middle/long term.

**Comment by eugeneloza** [comment]
Well... that seems reasonable...
However, the code is really horrible :) I never intended anybody but me ever see it :) And moreover, it doesn't use CGE too much now, only graphics and sound.
But... we'll fix that stuff later.
I think I'll be able to prepare the version history today evening and upload it tomorrow.
(Now I have only the latest version at hand, I'll have to check my home HDD to get all eralier versions, even those prior to sourcforge sources)

**Comment by akien-mga** [comment]
Awesome :D
I'm looking forward to a new version ported to recent CGE btw, I really liked the concept of this game. But I know you have to focus on other projects if you want to move your objectives forward with limited free time :)

**Comment by eugeneloza** [comment]
No, the problem is exactly the procrastination :D
However, I've got inspiration and work for 10-16 hours a day last week (almost 19 hours of effective work yesterday). But ~50% of this work is a scientific monograph and another ~50% is Decoherence plot (finally I've started to sort it and organize in google sites). No code... :(

**Comment by eugeneloza** [comment]
Your will has been fulfilled, Master! :jack_o_lantern:

**Comment by akien-mga** [comment]
Awesome work, even with full history :)

**Comment by eugeneloza** [comment]
And thanks for reminding me to do so. However, I was astonished, that I lacked earlier versions of the code. I was absolutely sure I kept all the track since the first lines... Maybe, they went missing when my HDD failed? Or did I record them to a DVD and discarded? Well... it doesn't matter already. Still, strange.
